- name: Clone restarters.net repository
  become: yes
  become_user: "{{ ssh_user }}"
  git: >
    repo=git@github.com:TheRestartProject/restarters.net.git
    dest="{{ application_path }}"
    key_file="{{ github_keyfile }}"
    accept_hostkey=yes
    update=yes
    version="{{ version }}"

- name: Install pip3, python3-dev, s3cmd packages with apt
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - python3-dev
    - python3-pip
    - s3cmd

- name: Upgrade latest setuptools, and docker-compose with pip
  become: true
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: setuptools, version: "latest", install: true }
    - { name: docker-compose, version: "latest", install: true }
  when: (item.version=="latest" and item.install)
  ignore_errors: yes

- name: Build and run docker services
  docker_service:
    project_src: "{{ application_path }}"
    build: yes
    state: present
    files:
      - "{{ deployment_env }}.yml"
